import { commands } from '../../data';

export default function statistics(list: Schema[]): void {
  const commandKeys = Object.keys(commands);
  const schema: Schema = {
    table: 'statistics',
    columns: [
      'ID',
      'name',
      'count',
    ],
    datatypes: [
      'INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY',
      'varchar(20) NOT NULL',
      'INT NOT NULL',
    ],
    values: [],
  };
  commandKeys.forEach((command: string) => {
    schema.values.push({
      name: command,
      count: 0,
    });
  });
  list.push(schema);
}
