"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.logLevel = exports.disableInitilizationOfDB = exports.disableDB = exports.commandPrefixAlias = exports.commandPrefix = exports.databaseUrl = exports.serverId = exports.owlBotToken = exports.token = void 0;
require("dotenv/config");
const token = process.env.TOKEN;
exports.token = token;
const owlBotToken = process.env.OWLBOT;
exports.owlBotToken = owlBotToken;
const serverId = process.env.SERVERID;
exports.serverId = serverId;
const databaseUrl = process.env.DATABASE_URL;
exports.databaseUrl = databaseUrl;
const commandPrefix = process.env.C_PREFIX;
exports.commandPrefix = commandPrefix;
const commandPrefixAlias = process.env.C_ALIAS;
exports.commandPrefixAlias = commandPrefixAlias;
const disableDB = !!process.env.DISABLE_DB;
exports.disableDB = disableDB;
const disableInitilizationOfDB = !!process.env.DISABLE_DB_INITILIZATION;
exports.disableInitilizationOfDB = disableInitilizationOfDB;
const logLevel = process.env.LOG_LEVEL;
exports.logLevel = logLevel;
